apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cluster-azure-apim-gateway
  namespace: fleet-default
spec:
  repo: https://github.com/raif-ahmed/fleet-apps.git
  branch: main
  paths:
    - /azure-apim-gateway

  targets:
  - name: aks
    clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-display-name
        operator: In
        values:
        - cluster-aks