apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cluster-longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/raif-ahmed/fleet-apps.git
  branch: main
  paths:
    - /longhorn

  targets:
  - name: rke
    clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-display-name
        operator: In
        values:
        - cluster-rke
        - cluster-rke2